# Copyright (C) 2025 Tiago V. L. Amorim (@tiagovla)
#
# This file is part of oiseau (https://github.com/tiagovla/oiseau)
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM node:20-slim

RUN npm install -g prettier

WORKDIR /work

ENTRYPOINT ["prettier"]
