---
name: CMake Build, Test and Analysis

on:
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/tiagovla/oiseau-baseline-builder:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure CMake with Ninja
              run: cmake -DOISEAU_BUILD_DOCS=OFF -DOISEAU_BUILD_COVERAGE=OFF -DOISEAU_BUILD_SHARED=OFF -S . -B build -G Ninja

            - name: Build with Ninja
              run: cmake --build build -- -j$(nproc)

            - name: Run tests
              run: ctest --test-dir build --output-on-failure

    clang-tidy:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/tiagovla/oiseau-baseline-builder:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure project to regenerate compile_commands.json
              run: cmake  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DOISEAU_BUILD_DOCS=OFF -DOISEAU_BUILD_COVERAGE=OFF -DOISEAU_BUILD_SHARED=OFF -S . -B build
                  -G Ninja

            - name: Run clang-tidy
              run: |
                  find src -name '*.cpp' | xargs -r -n 1 -P $(nproc) clang-tidy -p build --header-filter='^src/oiseau' 2>/dev/null

    cppcheck:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/tiagovla/oiseau-baseline-builder:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run cppcheck
              run: |
                  cppcheck --enable=all --std=c++20 --suppress=missingInclude --suppress=unmatchedSuppression --suppress=missingIncludeSystem --suppress=unusedFunction --error-exitcode=2 src -I src
