---
name: CMake Build, Test and Analysis

on:
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: sudo apt update && sudo apt install -y cmake ninja-build build-essential libblas-dev liblapack-dev libboost-all-dev libatlas-base-dev

            - name: Configure CMake with Ninja
              run: cmake -S . -B build -G Ninja

            - name: Build with Ninja
              run: cmake --build build -- -j$(nproc)

            - name: Run tests
              run: ctest --test-dir build --output-on-failure

    clang-tidy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install clang-tidy and build tools
              run: sudo apt update && sudo apt install -y clang-tidy cmake ninja-build build-essential libblas-dev liblapack-dev libboost-all-dev libatlas-base-dev

            - name: Configure project to regenerate compile_commands.json
              run: cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

            - name: Run clang-tidy
              run: |
                  find src -name '*.cpp' | xargs -r -n 1 -P $(nproc) clang-tidy -p build 2>/dev/null

    cppcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install cppcheck
              run: sudo apt update && sudo apt install -y cppcheck

            - name: Run cppcheck
              run: |
                  cppcheck --enable=all --inconclusive --std=c++23 --suppress=missingIncludeSystem --suppress=unusedFunction --error-exitcode=2 src -I src
