---
name: Deploy to GitHub Pages

on:
    push:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: sudo apt update && sudo apt install -y cmake ninja-build build-essential libblas-dev liblapack-dev libboost-all-dev libatlas-base-dev
                  gcovr doxygen

            - name: Configure CMake with Ninja
              run: cmake -DOISEAU_BUILD_TEST=ON -DOISEAU_BUILD_DOCS=ON -S . -B build -G Ninja

            - name: Build with Ninja
              run: cmake --build build -- -j$(nproc)

            - name: Prepare website structure
              run: |
                  mkdir -p website/docs
                  cp -r build/docs/html/* website/docs/

            - name: Run tests and generate coverage
              run: |
                  ctest --test-dir build --output-on-failure
                  mkdir -p website/coverage
                  gcovr --filter src/ --html-details -o website/coverage/index.html

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload website folder
              uses: actions/upload-pages-artifact@v3
              with:
                  path: website

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
